# Generated by Django 3.2.5 on 2021-08-12 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('cate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.category')),
                ('MG', models.TextField()),
            ],
            bases=('data.category',),
        ),
        migrations.CreateModel(
            name='Portfolio_projects',
            fields=[
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.images')),
                ('title', models.CharField(max_length=45)),
                ('thumbnail', models.TextField()),
            ],
            bases=('data.images',),
        ),
    ]
