# Generated by Django 3.2.5 on 2021-08-13 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('CT_Add', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Mess_name', models.CharField(max_length=50)),
                ('mess_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='professions',
            fields=[
                ('profession', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=35)),
                ('ser_des', models.TextField()),
                ('icon', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('client_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=60)),
                ('speech', models.CharField(max_length=56)),
                ('Tes_IMG', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('sk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.skills')),
                ('company_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('company_logo', models.TextField()),
                ('start_date', models.DateField()),
                ('Posision', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=('data.skills',),
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('EX', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.experiences')),
                ('Estart_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institution_name', models.CharField(max_length=45)),
                ('institution_logo', models.TextField()),
                ('education', models.CharField(max_length=25)),
                ('CGPA', models.FloatField()),
                ('Out_Of', models.FloatField()),
            ],
            bases=('data.experiences',),
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('AD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.educations')),
                ('ABOUT', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cv_link', models.CharField(max_length=150)),
                ('facebook_link', models.CharField(max_length=150)),
                ('linkdin_link', models.CharField(max_length=150)),
                ('github_link', models.CharField(max_length=150)),
            ],
            bases=('data.educations',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('PD', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.about')),
                ('PP', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.portfolio_projects')),
                ('SV', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.service')),
                ('con_CT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.contact')),
                ('TMT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.testimonials')),
                ('PRO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.professions')),
                ('ME', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='data.message')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
            ],
            bases=('data.about', 'data.portfolio_projects', 'data.service', 'data.contact', 'data.testimonials', 'data.professions', 'data.message'),
        ),
    ]
